# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html

# Site
title: 极客冲浪
keyword: 晨星 ,晨星的博客,晨星的小站
description: 晨星的小站，致力于分享一些技术教程和有趣的技术实践。
author: 极客冲浪
language: zh-CN

url: https://blog.k12on.com
root: /
permalink: post/:title.html

# seo优化各个浏览器的验证信息
#beian: 沪ICP备18001234号-1
seo_title: 极客冲浪 # 子页面的后缀，效果： 关于我 | 极客兔兔，如果与title一致，则可以不设置
seo:
  google_site_verification: 19ixTFj-X-rXuvZFvR1PMkqSHMXZ5GjN7nhYdYYFm-c
  baidu_site_verification: p7Pz3jlx4t
  ms_site_verification: 7E2AEE3378AC93764DEAB411177A21A1
  _360_site_verification: 5c7e8a1fdbf35ed6003c48733208f705 # 不能以数字开头，所以加上了下划线

# 开启博客资源的相对链接 https://hexo.io/zh-cn/docs/asset-folders
post_asset_folder: true

# Site settings
header_icon: img/icon.png

theme: geektutu

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/wandou911/wandou911.github.io.git
  branch: master

#gitalk:
  #client_id: 'c1fdd456a4caae5f7df0'
  #client_secret: 'b2674451e21feae50520f99337ec15d2aebe7879'
  #accessToken: 'xxxx'
  #repo: 'hexo-theme-geektutu'
  #owner: 'geektutu'

  # Valine Comment system. https://valine.js.org
valine:
  enable: true # 如果你想使用valine，请将值设置为 true
  appId:  VOVn3xhKE4eJL6TpShk8jfdi-gzGzoHsz # your leancloud appId
  appKey:  HJLyhFBsJDz6Ft5bTJnCG8nG # your leancloud appKey
  notify: true # Mail notify
  verify: true # Verify code
  avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: 要不要说点什么 # Comment Box placeholder
  guest_info: nick,mail # Comment header info： nick,mail,link
  pageSize: 10 # comment list page size

# alipay wechatpay 的二维码转换的网址，不使用二维码图片，提高加载速率。
# https://cli.im/deqr 可将二维码转为网址
reward:
  alipay: HTTPS://QR.ALIPAY.COM/FKX060337TUXBAX9LIFJE8
  wechat: wxp://f2f0qgGBlfD1nZXjvBjievxB0z0fc0W2sBq5

related_links:
- link: https://github.com/geektutu/hexo-theme-geektutu
  img: img/related_links/github.png
- link: https://zhuanlan.zhihu.com/geekgo
  img: img/related_links/go.png
- link: https://zhuanlan.zhihu.com/geektutu
  img: img/related_links/zhihu.png
- link: https://weibo.com/geektutu
  img: img/related_links/weibo.jpg

# 文章末尾配置一些提示信息，可选，不配置则不显示
post_tips:
  find_me: true # 本站永久域名「 xx.domain 」， 也可以通过搜索「 xx 」找到我。
  zhihu_zhuanlan: https://zhuanlan.zhihu.com/geektutu # 欢迎关注我的「 知乎专栏 」，所有文章可在「 知乎APP 」查看。
  weibo: https://weibo.com/geektutu # 欢迎关注我的「 微博 」。

widgets:
  mobile_qrcode: false # 开启移动端二维码，扫一扫，手机上阅读
  caidan: true  # 开启彩蛋，点击屏幕会随机弹出 '点个赞','留个言'等
  busuanzi: true # 开启不蒜子统计 https://busuanzi.ibruce.info/

# 自定义推广链接：宽度250，高度不限。
custom_ads:
- link: https://s.click.taobao.com/0ZEThqv
  img: https://img.alicdn.com/tfs/TB1QJC6dOrpK1RjSZFhXXXSdXXa-300-100.jpg
- link: https://url.cn/5bE04oI
  img: https://s2.ax1x.com/2020/02/12/1bns2D.jpg

ba_auto_push: true # Baidu 自动推送，以下均为可选配置
ba_track_id: 1a0ec33b1aa # Baidu Analytics
cnzz_track_id: 123649 # CNZZ Analytics
google_analysis: UA-141425-1 # Google Analytics
google_ad_client: ca-pub-939225546 # Google Ad